### ISSUE TITLE
Constant register limit exceeded at curr_res; more than 1024

### ISSUE THREAD

**Issue by Amrf000** [eduard-permyakov/permafrost-engine#10]
i got
```
Vertex info
-----------
(0) : error C6020: Constant register limit exceeded at curr_res; more than 1024
registers needed to compile program
```
then i reduce #define MAX_HBS   (512) to 500
but if there exsit any beter solution

**Comment by eduard-permyakov** [comment]
Set to 256 (guaranteed available in OpenGL spec). Currently, this is not a limitation. If it becomes a limitation, I will address it.
