### ISSUE TITLE
use malloc simlate VLA in M_AL_InitMapFromStream

### ISSUE THREAD

**Issue by Amrf000** [eduard-permyakov/permafrost-engine#11]
when i modfiy 
`char texnames[header->num_materials][256]; `
to` char (*texnames)[256] = (char(*)[256])malloc(header->num_materials * 256);`
there‘re  appear  some confusing exception in stb,
then i use just a static array` char texnames[64][256]; `things become okay;

**Comment by eduard-permyakov** [comment]
I am not removing VLAs from the code currently
