### ISSUE TITLE
crash on start on linux

### ISSUE THREAD

**Issue by draczer01** [eduard-permyakov/permafrost-engine#16]
I get the following errors when trying to execute
`make run` or `make run_editor`

`Failed to initialize GLEW
Makefile:186: recipe for target 'run' failed
make: *** [run] Segment violation
`

I have already compiled the dependencies and the pf engine

**Comment by eduard-permyakov** [comment]
Fixed in commit: 4c544857ba16af2c369e50ca0e5d4310b011bb54 
(https://github.com/eduard-permyakov/permafrost-engine/commit/4c544857ba16af2c369e50ca0e5d4310b011bb54)
Thanks for the bug report and assistance.

**Comment by draczer01** [comment]
the issue persists in the new update

**Comment by eduard-permyakov** [comment]
now fixed.
