### ISSUE TITLE
no conf file or it is searched in the wrong directory

### ISSUE THREAD

**Issue by draczer01** [eduard-permyakov/permafrost-engine#17]
I get the following error when running 

`Could not load settings from file: .//pf.conf [status: 3]`

I was able to solve this simply by creating a pf.conf file on the main directory, but since this was a blank file my guess is that no configuration is being loaded or that default values are being used, also I wasn't able to find any pf.conf file on the code

**Comment by eduard-permyakov** [comment]
This isn't an error. Any time that the pf.conf file is not found (such as the first time you boot the engine), the pf.conf file is created with the default values. The message is simply for information, but I guess I should make it clearer that this isn't a fatal error. When you exit from the engine, the current state of persistent settings will be written to the pf.conf file.

The name "pf.conf" is defined in config.h and the logic for working with the settings file is in settings.c.
