### ISSUE TITLE
Migration from Python 2.7 up to 3.x

### ISSUE THREAD

**Issue by tujh-rf** [eduard-permyakov/permafrost-engine#24]
>Engine internals exposed to Python 2.7 for scripting

Python 2 is not supported anymore, a lot of Linux distributions provided without Python2 by default - Ubuntu 20.04 for example.

>We needed to sunset Python 2 so we can help Python users by improving Python faster.
https://www.python.org/doc/sunset-python-2

Maybe it's time to move to Python 3 ?

**Comment by eduard-permyakov** [comment]
The engine requires a modified version of Python 2.7 that is in-tree. So it is independent from the default Python version provided by your distribution. As a large amount of code has already been written against the Python 2.7 C API, the change is difficult and not practical.
