### ISSUE TITLE
Python Wrapper

### ISSUE THREAD

**Issue by ma7dev** [eduard-permyakov/permafrost-engine#28]
Awesome project! I have always liked playing Age of Empires and I admire your work by having a similar game.

I am currently interested in training agents to play the game. After looking into the project source code, I have noticed that the project uses python but it doesn't have a python wrapper like https://github.com/google-research/football where you can interact with the engine. 

I think having a python wrapper will enable researchers to use the game to train agents to play the game and this will be a great environment to experiment on!

Are you planning to have a python wrapper implemented? Can the community try to tackle this? Thanks!

**Comment by eduard-permyakov** [comment]
I've got a fully-featured interactive Python console in the latest version now.
