### ISSUE TITLE
g_init_cameras  missing return

### ISSUE THREAD

**Issue by Amrf000** [eduard-permyakov/permafrost-engine#9]
static bool g_init_cameras(void) 
{
    for(int i = 0; i < NUM_CAMERAS; i++) {
    
        s_gs.cameras[i] = Camera_New();
        if(!s_gs.cameras[i]) {
            return false;
        }

        Camera_SetSpeed(s_gs.cameras[i], CAM_SPEED);
        Camera_SetSens (s_gs.cameras[i], 0.05f);
        g_reset_camera(s_gs.cameras[i]);
    }
}

**Comment by eduard-permyakov** [comment]
Fixed
